#ifndef CONSTANTS_H
#define CONSTANTS_H

#define HEIGHT 25 
#define WIDTH 75
#define AMOUNT_OF_MONS 20

#define WARRIOR_STRENGTH 13
#define WARRIOR_INTELLIGENCE 2

#define MAGE_STRENGTH 4
#define MAGE_INTELLIGENCE 11

#define PALADIN_STRENGTH 9
#define PALADIN_INTELLIGENCE 6

#define GOBLIN_HP 10
#define GOBLIN_STRENGTH 3

#define DRAGONKIN_HP 30
#define DRAGONKIN_STRENGTH 8

#define DEATHKNIGHT_HP 20
#define DEATHKNIGHT_STRENGTH 6

#define UP_ARROW 72
#define LEFT_ARROW 75
#define RIGHT_ARROW 77
#define DOWN_ARROW 80
#define ENTER 13

#define AMOUNT_GOBLINS 7
#define AMOUNT_DRAGONKIN 7
#define AMOUNT_DEATHKNIGHT 6

#define MAX_OPTIONS_IN_MENU 4
#define MAX_OPTIONS_IN_HEROES_MENU 3

#endif
